language: node_js
dist: bionic
sudo: required

node_js:
- '11'

env:
  matrix:
  - PATH=$HOME/purescript:$PATH

install:
- npm install i
- spago install

script:
- export VERSION=branch-job-$TRAVIS_JOB_NUMBER
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then export VERSION=pull-request-job-$TRAVIS_JOB_NUMBER;
  fi
- if [[ "$TRAVIS_TAG" != "" ]]; then export VERSION=$TRAVIS_TAG; fi
- rm -rf bower_components output
- spago build
- spago test

cache:
  directories:
  - output
